### ISSUE TITLE
Start Calibre maximized

### ISSUE THREAD

**Issue by dkadioglu** [linuxserver/docker-calibre#100]
## Desired Behavior
Start Calibre as maximized window. 

## Current Behavior
Calibre is not started as maximized and as a smaller window in the top left corner of the browser window. 

## Alternatives Considered
Manually maximizing the window works but, this is not persistent. After a restart of the container, the window is again not maximized. 

I am using the Arch version on aarch64.

**Comment by dkadioglu** [comment]
Calming the stale bot.
As there was no reply so far, may I ask again, what your opinion about this is?

**Comment by aptalca** [comment]
@dkadioglu 
Can you test this image and let us know if it works or not?
`lspipepr/calibre:v6.6.1-pkg-b374489f-pr-107`

**Comment by dkadioglu** [comment]
@aptalca 
Works as intended, Calibre starts maximized. Thank you very much for implementing this! Can this be implemented for the Arch based version of the image, too?

By the way: What is the future perspective of the Arch based version? Is it just some current experiment, or do you plan to establish it as an permanent alternative to the Ubuntu based version? (I hope, it is ok, to ask this here.)

**Comment by aptalca** [comment]
Arch tag was only released because calibre wasn't available for arm devices on Ubuntu. But now calibre is available on aarch64 and the arch calibre was deprecated for armhf. So they currently have feature parity and therefore we will be deprecating the arch tag soon.

Thanks for testing and confirming.
