### ISSUE TITLE
Headless automatic start of Calibre Content Server

### ISSUE THREAD

**Issue by gerpy** [linuxserver/docker-calibre#103]
## Desired Behavior
Calibre Content Server starting automatically when the container starts

## Current Behavior
To start the Content Server, I need to start the Guacamole UI first. I would like a permanent, automatic and headless content server.

## Alternatives Considered
There is perhaps alrady a way to do this, may be by passing adequate CLI_ARGS, but I couldn't find any helpfull documentation.

**Comment by aptalca** [comment]
It already does. But you need to enable it and set it to auto start in gui settings

**Comment by gerpy** [comment]
Thanks a lot fot the input. It works like a charm, behind an inverse proxy and with authentification. This opens up possibilities. Great !
