### ISSUE TITLE
ownership changes running always in 6.6

### ISSUE THREAD

**Issue by meatsac** [linuxserver/docker-calibre#108]
I have the /config directory on a NFS share and work around the ownership issue by ensuring the permissions are 1000:1000 on the NFS mount. This ensures that the update script doesn't need to change them. 

This works on 6.3, 6.4 but on the current release the ownership change always runs and results in the error below. 

chown: changing ownership of '/config': Operation not permitted

Reverting back to the previous image works.

**Comment by aptalca** [comment]
We don't support putting config folders on remote shares

**Comment by meatsac** [comment]
Understandable. Just wanted to capture the change in functionality. It used to be that it would only attempt to change the owernship and permissions if needed. Now it seems to attempt this every time.
