### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by Gerben-W** [linuxserver/docker-calibre#11]
After deploying the application through Unraid 6.7.2 APPS, i'm getting the following error in the log.

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Tried to deploy the application with Network Type host and Custom. Both give the same error

**Comment by MTuner** [comment]
I have the same issue with the v4.0.0-ls24 release (latest at the moment).
The previous version (v3.48.0-ls24) works.

**Comment by MTuner** [comment]
Thank you @tomusher, I can confirm that the #12  solves the issue.
