### ISSUE TITLE
calibre ports refused on ipv6

### ISSUE THREAD

**Issue by dsm1212** [linuxserver/docker-calibre#113]
Using the todays latest (c58aad8137bb) in a container with ipv6 enabled, the calibre port is "connection refused". Both the web and api ports respond this way. Actually the service doesn't start. After chatting on discord it seems this is an issue with the base image and IPV6 that was introduced about a month ago. Temp work around is to disable ipv6. Just recording here because I don't see an issue for it.

**Comment by antoniocamas** [comment]
> Using the todays latest (c58aad8137bb) in a container with ipv6 enabled, the calibre port is "connection refused". Both the web and api ports respond this way. Actually the service doesn't start. After chatting on discord it seems this is an issue with the base image and IPV6 that was introduced about a month ago. Temp work around is to disable ipv6. Just recording here because I don't see an issue for it.

Hello dsm1212

How do I disable ipv6 in the container?

I beliver I am suffering the same issue.

**Comment by antoniocamas** [comment]
> Our images are getting updated, but because there are multiple layers of baseimages, it takes some time to waterfall. It will be fixed soon. Until then, you can switch to an older calibre tag

Thanks, I will do so!

**Comment by dsm1212** [comment]
In the container you can also temporarily add:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
