### ISSUE TITLE
Docker Copose Install fails when extracting images. (Downloads complete then fail to extract)

### ISSUE THREAD

**Issue by Bugmaniac71** [linuxserver/docker-calibre#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Any image fails to install with:

failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /tmp/out: invalid argument

root@ct-dockeru:/opt# dcup
[+] Running 11/16
 ⠹ calibre Pulling                                                                                                                                                          38.3s
   ⠿ 22a27b72561c Already exists                                                                                                                                             0.0s
   ⠿ c61fe2056171 Already exists                                                                                                                                             0.0s
   ⠿ b2a8d31e5e63 Already exists                                                                                                                                             0.0s
   ⠿ 186de441dbe3 Already exists                                                                                                                                             0.0s
   ⠿ 1a22441c4a2f Already exists                                                                                                                                             0.0s
   ⠿ 7a8c8bd3bdf1 Pull complete                                                                                                                                              2.1s
   ⠿ 9c8972fbb475 Pull complete                                                                                                                                              6.7s
   ⠿ 94553e7e2f71 Pull complete                                                                                                                                             13.9s
   ⠿ 01ca919838b6 Pull complete                                                                                                                                             18.9s
   ⠿ f6a32d3ac33e Pull complete                                                                                                                                             24.1s
   ⠿ 63d138525a11 Pull complete                                                                                                                                             29.2s
   ⠦ 57b739e04ede Extracting      [==================================================>]  68.58MB/68.58MB                                                                    35.6s
   ⠦ 27effbe58833 Download complete                                                                                                                                         35.6s
   ⠦ 79d4e6af8d3b Download complete                                                                                                                                         35.6s
   ⠦ 7259b0037b75 Download complete                                                                                                                                         35.6s
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /tmp/out: invalid argument

### Expected Behavior

Install should complete

### Steps To Reproduce

docker compose up fails everytime

### Environment

```markdown
Proxmox 7.3.6 -> Ubuntu LXC -> Docker :
```

### CPU architecture

x86-64

### Docker creation

```bash
calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=2021
      - PGID=2000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /opt/app_data/calibre:/config # Where calibre-web stores the internal database and config.
#      - /opt/app_data/plex/media/books:/books # Where your preexisting calibre database is located.
    ports:
      - 8087:8080
      - 8088:8081
    restart: unless-stopped
#    security_opt:
#      - seccomp:unconfined # For Docker Engine only, many modern gui apps need this to function as syscalls are unkown to Docker.
    networks:
      test_network:
        ipv4_address: 192.168.1.122
```

### Container logs

```bash
Doesnt get that far.
```

**Comment by aptalca** [comment]
That looks like it has nothing to do with our image. It's an issue with your system and docker install.

Fwiw, proxmox doesn't recommend running docker in lxc: https://forum.proxmox.com/threads/docker-failed-to-register-layer-applylayer-exit-status-1-stdout-stderr-unlinkat-var-log-apt-invalid-argument.119954/#post-521620

**Comment by Bugmaniac71** [comment]
OK seems a bit of a cop out though as every other image i use works fine.
I know Proxmox dont recommend using LXC for Docker but theres plenty of stable installations out there hence why I went that route. Will try it with a VM though, thanks.
C

**Comment by aptalca** [comment]
If by cop out you're referring to my response, just do a google search for the error and you'll see tons of reports with all sorts of different images, but all on proxmox lxc:
https://www.google.com/search?q=failed+to+register+layer%3A+ApplyLayer+exit+status+1+stdout%3A+stderr%3A+unlinkat+%2Ftmp%2Fout%3A+invalid+argument

Nothing we can do as it can't even pull the image properly
