### ISSUE TITLE
[FEAT] KASMVNC... Just Why?

### ISSUE THREAD

**Issue by truthsword** [linuxserver/docker-calibre#131]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Long time calibre user, and now I have KASMVNC appearing on launch. Why? What does this do for me? Can it be disabled? I'm no longer sure of my security when a new kid pops on the scene. 

Is there an announcement I missed? Thanks!

### Reason for change

Just why.

**Comment by aptalca** [comment]
https://www.linuxserver.io/blog/webtop-2-0-the-year-of-the-linux-desktop

tl:dr KasmVNC is a new alternative to the xrdp/guacamole/gclient combo we were using in our gui based images.
