### ISSUE TITLE
[FEAT] Support for KFX Output plugin (requires wine)

### ISSUE THREAD

**Issue by PozoSer** [linuxserver/docker-calibre#144]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

KFX on Kindle readers add several quality of life benefits such as Enhanced Typesetting, multi-thumbnail Page Flip, non-justified alignment, continuous scrolling, page curl, Guided View for comics, and sticky notes (on Kindle Scribe).

There is already a plug-in to convert books to KFX format, but I believe wine is required. Official thread: https://www.mobileread.com/forums/showthread.php?t=272407

As per the official documentation: 

"The Linux platform is not supported by the Kindle Previewer, however the Windows version can be installed under Wine. The Previewer can be used to perform conversions in spite of it producing numerous "DEBUG" and "fixme" messages. Because calibre needs to be able to invoke Wine it is unlikely to work if calibre is installed within a container such as Flatpak, Snap, or AppImage. The most recently tested working configuration is Kindle Previewer 3.60 and wine-7.0-rc4 running on Gentoo 5.15.12. Other software combinations are untested and may not work. The Previewer's GUI does not function under Wine."

### Reason for change

Several quality of life benefits such as Enhanced Typesetting, multi-thumbnail Page Flip, non-justified alignment, continuous scrolling, page curl, Guided View for comics, and sticky notes (on Kindle Scribe).

**Comment by aptalca** [comment]
Wine is not something we will add to the image.

But you can try and add it yourself: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
Also: https://github.com/linuxserver/docker-mods/tree/universal-package-install
