### ISSUE TITLE
[FEAT] Calibre-server variant

### ISSUE THREAD

**Issue by satmandu** [linuxserver/docker-calibre#146]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be nice to have a docker-calibre variant that only runs the `calibre-server` binary since that can be used just for running the calibre web interface.

### Reason for change

The calibre binary and the calibre server binaries cannot be run simultaneously, so it would be nice to have an option we could pass to the container to run `calibre-server` instead of `calibre`. 

https://manual.calibre-ebook.com/generated/en/calibre-server.html

**Comment by aptalca** [comment]
Calibre server can be enabled in the gui. The readme explains this.

We have no plans for a separate image with just the calibre server.
