### ISSUE TITLE
[FEAT] Auto relaunch calibre windows in case of closing

### ISSUE THREAD

**Issue by stefore** [linuxserver/docker-calibre#150]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Is this a way to auto launch Calibre if we close it ?

### Reason for change

Need to restart the container in case of closing Calibre

**Comment by j0nnymoe** [comment]
Right clicking should bring up a menu to reopen calibre.

**Comment by stefore** [comment]
indeed, it works. Thanks :)
