### ISSUE TITLE
Add PDF viewer to docker image

### ISSUE THREAD

**Issue by cplerch** [linuxserver/docker-calibre#151]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

There is no pdf viewer installed for viewing Calibre PDF e-books. Adding one to the image would be helpful.

### Reason for change

Usability enhancement

### Proposed code change

Perhaps via DOCKER_MODS? Could be useful for other images too.

**Comment by christian-smith** [comment]
Just add either okular or xpdf as a package to the environment variables. Okular supports PDF annotations.
```
environment: 
  - DOCKER_MODS=linuxserver/mods:universal-package-install
  - INSTALL_PACKAGES=okular
```
