### ISSUE TITLE
[FEAT] Recommend additional /books mount to avoid polluting with home directory files

### ISSUE THREAD

**Issue by valankar** [linuxserver/docker-calibre#152]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The readme states to use a `/config` mount point for Calibre's database and library. This directory seems to end up as the home directory and gets polluted with directories such as `ssl` and `.cache`. It is not a great location to store books. A better recommendation would be to mount `/books` as well and use that for the book/database location, and keeping the `/config` separate for the docker container files.

### Reason for change

Seeing `ssl` directory in my books location with the private key surprised me. Also `.cache`, etc which had nothing to do with books.

**Comment by aptalca** [comment]
That folder is meant to be _Calibre_'s library. Not _yours_. 

You view the calibre library through its gui or through companion apps like calibre-web.

**Comment by llwt** [comment]
For anyone coming to this with a similar concern, you can always map another directory and use that instead when configuring Calibre.

e.g.
```yml
volumes: 
- /home/llwt/.config/calibre:/config
- /home/llwt/media/books:/books 
```

![image](https://github.com/linuxserver/docker-calibre/assets/1036428/b374b066-bd91-4507-83df-5c01e7455eb9)
