### ISSUE TITLE
[FEAT] calibre favicon

### ISSUE THREAD

**Issue by r3mi** [linuxserver/docker-calibre#156]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Thanks for this useful container !
Is there a way to set the browser's favicon to be calibre icon ?
Currently it is a greyed-out kasm icon.

### Reason for change

To more easily identify the calibre browser tab

**Comment by JamieCristofani** [comment]
Does a comment here unmark this issue as stale? I would love an accurate favicon.
