### ISSUE TITLE
Web browser tab title needed

### ISSUE THREAD

**Issue by orsomething1030** [linuxserver/docker-calibre#16]
## Expected Behavior

The web browser tab should be "Calibre" or something like that so it's easily identifiable.
## Current Behavior

The web brower tab is named "127.0.0.1"
## Steps to Reproduce

1.  Open web browser to calibre docker ip address:port

**Comment by CHBMB** [comment]
I don't know how feasible this will be, as you're actually opening a web browser to a guacamole remote desktop, which then displays Calibre

**Comment by orsomething1030** [comment]
The deprecated aptalca/docker-rdp-calibre container, which I assume this one is based off of, shows Calibre in the browser tab.  That's only reason I noticed to be honest.

**Comment by CHBMB** [comment]
@aptalca Would be better placed to answer, but I think the internals are a fair bit different between the two, I could, however, be completely & utterly wrong.

**Comment by Esvent** [comment]
### Right way (currently unavailable)

The guacamole title on browser reflects connection name which set in `/etc/guacamole/user-mapping.xml`

Example:
```xml
<user-mapping>
    <authorize
            username="GUAC_USER"
            password="GUAC_PASS"
            encoding="md5">
        <!-- Add connection element for your favorite name, otherwise the title would be "DEFAULT" -->
        <connection name="Calibre">
            <protocol>rdp</protocol>
            <param name="hostname">127.0.0.1</param>
            <param name="port">3389</param>
            <param name="color-depth">16</param>
            <param name="ignore-cert">true</param>
            <param name="username">abc</param>
            <param name="password">abc</param>
        </connection>
    </authorize>
</user-mapping>
```

Unfortunately, this only works while connecting state. Once you get into the Calibre UI, the title would be replace with hostname (127.0.0.1) immediatly.
It's a bug of Guacamole  0.9.13 -  0.9.14, see [GUACAMOLE-502](https://issues.apache.org/jira/browse/GUACAMOLE-502).

This should work at Guacamole 1.0.0 and later (not tested)

### Workaround

We could manually assign a identifiable hostname to container itself by modify `/etc/hosts` in container (or use --volume to replace one), and then change the hostname setting in `/etc/guacamole/user-mapping.xml` to use it.

Note. 
Docker container usually has a hostname just like container name to itself by default, so editing hosts is not always necessary.

**Comment by aptalca** [comment]
no longer relevant due to baseimage change
