### ISSUE TITLE
PUID/PGID setting to 1032/100 fails to start

### ISSUE THREAD

**Issue by rcarmo** [linuxserver/docker-calibre#20]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

The container should start regardless of values

## Current Behavior

The container enters a crash loop with the following output:

```
chansrv::main: using log file [/tmp/xrdp-chansrv.1.log]                                            
Could not start log                                                                                
error opening log file [The log is not properly started]. quitting.                                
chansrv::main: using log file [/tmp/xrdp-chansrv.1.log]                                            
Could not start log                                                                                
error opening log file [The log is not properly started]. quitting.                                
chansrv::main: using log file [/tmp/xrdp-chansrv.1.log]                                            
Could not start log                                                                                
error opening log file [The log is not properly started]. quitting.                                
```

## Steps to Reproduce

1. Install container on Synology NAS
2. Set environment variables PUID/PGID to 1032/100
3. Start it

## Environment
**OS:** Synology DSM 6.x
**CPU architecture:** x86_64   
**How docker service was installed:**      Built in to DSM

## Command used to create docker container (run/create/compose/screenshot)

![image](https://user-images.githubusercontent.com/392683/71754215-313b9700-2e7d-11ea-9c80-40169b4892f1.png)

**Comment by tobbenb** [comment]
The container will not start correctly if the wrong PUID and PGID is used. 
You have to use the PUID and PGID that have access to the host foldcer of /config.

**Comment by rcarmo** [comment]
The reason I set the UID/GID was precisely that. I need to use that UID to access both the /config volume and a separate /books volume that is created by that UID.

**Comment by tobbenb** [comment]
Please supply information about the whole setup of the container, not only the Env variables.
Also show the output of ls -al for the host /config folder.

**Comment by rcarmo** [comment]
Here you go, the remaining settings screens plus a terminal window. The permissions inside /config are correct, as you can see.

<img width="658" alt="Screenshot 2020-01-04 at 11 51 26" src="https://user-images.githubusercontent.com/392683/71765142-d5a6f300-2ee8-11ea-8a0b-99bbfdaa8e67.png">
<img width="654" alt="Screenshot 2020-01-04 at 11 51 31" src="https://user-images.githubusercontent.com/392683/71765143-d63f8980-2ee8-11ea-8f72-f2459b864e48.png">
<img width="658" alt="Screenshot 2020-01-04 at 11 51 37" src="https://user-images.githubusercontent.com/392683/71765144-d63f8980-2ee8-11ea-8294-4c3302480a2c.png">
<img width="656" alt="Screenshot 2020-01-04 at 11 51 44" src="https://user-images.githubusercontent.com/392683/71765145-d63f8980-2ee8-11ea-84d8-39c1633a6b27.png">
<img width="1082" alt="Screenshot 2020-01-04 at 11 52 22" src="https://user-images.githubusercontent.com/392683/71765146-d6d82000-2ee8-11ea-8f2a-6f49b1b5a771.png">

**Comment by rcarmo** [comment]
The Synology log dumps are HTML and finicky to work with, but  I'm also attaching a log dump in which you can see the following line:

```
QStandardPaths: wrong ownership on runtime directory /tmp/runtime-abc, 911 instead of 1032
```

This leads me to believe that `s3-init` (or something else) is not changing permissions on `/tmp` correctly.

<img width="1489" alt="Screenshot 2020-01-04 at 12 04 58" src="https://user-images.githubusercontent.com/392683/71765287-75b14c00-2eea-11ea-95f2-74d4e610e3a5.png">

**Comment by tobbenb** [comment]
The permissions should be abc:abc, not abc:users. That might be an issue.
As for /tmp, I'm not sure what is going on there. It's for sure wrong permissions.

**Comment by rcarmo** [comment]
Well, /tmp is inside the container.

**Comment by tobbenb** [comment]
I just tested it here and it works as it should.
Are you sure that the user (UID 1032) have permission to read/write/execute in the host folder of /config?
What is the output of ls -al / and ls -al /tmp inside the container?
Please also post the output of ls -al in the host folder for /config.

**Comment by geiger-engineering** [comment]
I've had the exact same problem (using PUID of 1032). I'm not sure why, but deleting all content on the container (right click on container -> action -> delete content [not sure this is the correct name; my Syno is in German]) fixed the problem for me. Maybe it is connected to the Syno logs? I first ran the container with the default user and then modified the environment with the correct PUID/GUID without deleting the container.

**Comment by tobbenb** [comment]
That makes sense. As the files were created first using one user's UID and then changed. That would make it not accessible

**Comment by rcarmo** [comment]
I have since updated the container image and the container now starts for me.
