### ISSUE TITLE
Support armhf architecture

### ISSUE THREAD

**Issue by lcd1232** [linuxserver/docker-calibre#21]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
DockerHub should have armhf architecture and tag `arm32v7-latest`.

## Current Behavior
Right now there is no support for armhf architecture

**Comment by j0nnymoe** [comment]
Calibre don't publish binaries for that platform.
