### ISSUE TITLE
Passing Arguments to Calibre Server

### ISSUE THREAD

**Issue by reverendj1** [linuxserver/docker-calibre#24]
Is there any way to pass arguments to the Calibre Server? Specifically I'm looking for a way to pass `--auth-mode=basic` to the server, since I am running it behind an SSL reverse proxy. There doesn't seem to be an option in the preferences, the only way you can use it is via the command line argument.

**Comment by bruns01** [comment]
I'd like to support this request and hope for a solution.
I have various services behind a reverse proxy and need the
--url-prefix /some_prefix
option of calibre-server.
Thanks in advance

**Comment by aptalca** [comment]
We'll add that functionality, but I got other urgent things on my plate, so it will be a few days or a couple weeks before I get to it

**Comment by reverendj1** [comment]
Awesome. Thank you!

**Comment by reverendj1** [comment]
@aptalca It's been a few weeks and I didn't see any changes related to this, so here's your ping for when you have time. Thanks!
