### ISSUE TITLE
Allow OAuth plugins login functionality

### ISSUE THREAD

**Issue by daften** [linuxserver/docker-calibre#25]
Now plugins like goodreads can't work AFAIK, since clicking authorize, doesn't do anything, there is no browser to be started. It would be nice if that could happen through the browser with which you eat the guacamole server.

**Comment by daften** [comment]
ping, since issues without any action become stale

**Comment by aptalca** [comment]
You can add a browser via customization, but we won't add it to the image as they're often huge with lots of dependencies
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by Millio345** [comment]
For anyone reading this in the future. To get the goodreads plugin working, you don't need to actually install a browser in the container.

Open the log at /config/.xsession_errors and copypaste the URL (For goodreads it starts with 'http://www.goodreads.com/oauth/authorize/' ) from there to open in a web browser on any device and authorize from there.
