### ISSUE TITLE
Unable to open PDFs in calibre on Ubuntu 20.04 and macOS 10.15.4

### ISSUE THREAD

**Issue by delize** [linuxserver/docker-calibre#29]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Ability to open PDF files

## Current Behavior
PDF does not open and produces error in docker logs, same file is able to be read by linuxserver/calibre-web
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'
Unable to detect a launcher for 'file:///config/Calibre Library/....pdf'
```

## Steps to Reproduce

1. Upload PDF
2. Attempt to open PDF

These have been the same steps for 5 different PDF files

## Environment
**OS:**  Ubuntu 20.04.0 LTS, macOS 10.15.4
**CPU architecture:** x86_64
**How docker service was installed:**      https://docs.docker.com/engine/install/ubuntu/ , https://docs.docker.com/docker-for-mac/install/

On Ubuntu systems are mounted on mergerfs file systems, on macOS, it is using the main SSD without any fuse based filesystems.

## Command used to create docker container (run/create/compose/screenshot)
ubuntu:
```
sudo docker create   --name=calibre   -e PUID=1000   -e PGID=1000   -e TZ=America/Los_Angeles   -e GUAC_USER=user   -e GUAC_PASS=passwordhash   -e UMASK_SET=022   -p 8080:8080   -p 8081:8081   -v /mnt/mergerfs/calibre:/config   -v /mnt/rclone/gebooks/books:/books   --restart=unless-stopped   linuxserver/calibre:latest
```

macOS:
```
sudo docker create   --name=calibre   -e PUID=1000   -e PGID=1000   -e TZ=America/Los_Angeles   -e GUAC_USER=user   -e GUAC_PASS=passwordhash   -e UMASK_SET=022   -p 8080:8080   -p 8081:8081   -v /Users/user/Documents/docker/calibre:/config   -v /Users/user/Downloads:/books   --restart=unless-stopped   linuxserver/calibre:latest
```
## Docker logs
Exceptional Lines:
Line 922 is error, 
lines after 922 are opening up an epub file successfully (albeit slowly). 
Lines of somewhat (opinionated) importance 283, line 308.
[full_docker_calibre.log](https://github.com/linuxserver/docker-calibre/files/4685838/full_docker_calibre.log)

**Comment by delize** [comment]
I did do some research on this, though I am not sure how related they area:
http://murga-linux.com/puppy/viewtopic.php?p=1018664&sid=36d6710ec80d1eaeb12b145a84d50c60
https://bugs.archlinux.org/task/56547

**Comment by drizuid** [comment]
pasting my comments from discord:
```
[10:01 PM] driz: click preferences -> behavior -> on the right tab (use internal viewer for) select pdf, hit apply
[10:01 PM] driz: then close
[10:01 PM] driz: then your pdf should open
```

I will look into boot time flags or something to see if we can set this as a default.

**Comment by drizuid** [comment]
i did some research and I'm not finding a way, thus far, i've not found a method to adjust the setting via CLI, config file, or environment variables. We may just need to put a snip in the readme.

**Comment by drizuid** [comment]
as this is a standard/default function of using calibre with a standard method of enabling it, im going to close this.
