### ISSUE TITLE
Unable to start the docker container.

### ISSUE THREAD

**Issue by beltet** [linuxserver/docker-calibre#31]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

I'm trying to start the calibre docker container but gets a error message.

------------------------------

## Expected Behavior
After setting up  the container, it should start with the command:
`sudo docker run calibre`

## Current Behavior
I get a error message when trying to run it:
```
Unable to find image 'calibre:latest' locally
docker: Error response from daemon: pull access denied for calibre, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

## Steps to Reproduce

1. `docker pull linuxserver/calibre`
output:
```
Using default tag: latest
latest: Pulling from linuxserver/calibre
19015790457d: Pull complete 
f9e378595204: Pull complete 
5231853fdcfa: Pull complete 
3bbf420e6b63: Pull complete 
bfa29afd12e0: Pull complete 
f73e207bc697: Pull complete 
ea8e64ae15e2: Pull complete 
42d6d6dbc4cf: Pull complete 
f56af5956c05: Pull complete 
77ce228d4a09: Pull complete 
439e3d7f74fc: Pull complete 
Digest: sha256:d3665a8843033ecf33bed57548502fb10002acace56ec5a91797e09d6cb35fd3
Status: Downloaded newer image for linuxserver/calibre:latest
docker.io/linuxserver/calibre:latest
```

2. Create a executable `calibre_server.sh` with the data:
```
docker create \
  --name=calibre \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Stockholm \
  -e GUAC_USER=myusername `#optional` \
  -e GUAC_PASS=mygeneratedpassword `#optional` \
  -e UMASK_SET=022 `#optional` \
  -e CLI_ARGS= `#optional` \
  -p 8082:8082 \
  -p 8083:8083 \
  -v /home/myusername/calibre_data:/config \
  --restart unless-stopped \
  linuxserver/calibre
```

3. Run `calibre_server.sh` and check  that calibre is created with `sudo docker ps -a `

4. Try to start it with `sudo docker run calibre`
gives output:
```
Unable to find image 'calibre:latest' locally
docker: Error response from daemon: pull access denied for calibre, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

## Environment
OS: Ubuntu 20.04 LTS x86_64
Host: BHYVE 1.0 
Kernel: 5.4.0-28-generic
Shell: bash 5.0.16
CPU architecture: x86_64
CPU: Intel Xeon E3-1220 v3 (1) @ 3.090GHz 
How docker service was installed: apt

## Command used to create docker container (run/create/compose/screenshot)
password was generated on local computer.
checked that my user had PUID/GUID 1000 on remote machine.

## Docker logs
`sudo docker logs calibre` gave no output

**Comment by aptalca** [comment]
Use `docker start calibre`
