### ISSUE TITLE
missing packages in current image

### ISSUE THREAD

**Issue by santalucial** [linuxserver/docker-calibre#35]
## Expected Behavior
it should start

## Current Behavior
Calibre won't run untill required packages are installed with
apt-get install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0

## Command used to create docker container (run/create/compose/screenshot)
docker create \
  --name=calibre \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -p 8080:8080 \
  -p 8081:8081 \
  --restart unless-stopped \
  linuxserver/calibre

## Docker logs
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

**Comment by j0nnymoe** [comment]
already been fixed. https://github.com/linuxserver/docker-calibre/pull/34
