### ISSUE TITLE
Run only the content server?

### ISSUE THREAD

**Issue by Diaoul** [linuxserver/docker-calibre#38]
Would it be possible to run only the content server of calibre? If so, should this be an option in this image or should it be a separate image?

**Comment by aptalca** [comment]
Not possible with this image. If you want just a webserver, you can look into calibre-web or cops

**Comment by Diaoul** [comment]
I meant the [calibre content server](https://manual.calibre-ebook.com/server.html#the-calibre-content-server) which is part of calibre, not some 3rd party tool that reuses the database file.
Having multiple applications using the same database causes locking issues.

**Comment by danielwagn3r** [comment]
You can configure calibre to run the content server on startup, when #44 is fixed this image does what you are trying to do

**Comment by aptalca** [comment]
> I meant the calibre content server which is part of calibre, not some 3rd party tool that reuses the database file.
Having multiple applications using the same database causes locking issues.

You're asking about only running the calibre content server. I'm suggesting using calibre-web only (or cops only), not multiple things accessing it at the same time.

In any case, currently not possible and no plans to add the original request. Also the content server needs to first be enabled in calibre settings.
