### ISSUE TITLE
zombie process s6-notifyonchec

### ISSUE THREAD

**Issue by meLIanTQ** [linuxserver/docker-calibre#39]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

zombie process high ram usage
------------------------------

## Current Behavior

zombie process high ram usage
## Steps to Reproduce

1. just pull the image and run
docker run -d \
  --name=calibre \
  --restart unless-stopped \
  -e PUID=1000 \
  -e PGID=1000 \
  -e GUAC_USER=user \
  -e GUAC_PASS=pass \
  -p 8080:8080 \
  -p 8081:8081 \
  -v /pathtoconfig:/config \
  -v /othermount:/mnt/calibre \
  ghcr.io/linuxserver/calibre

after this the calibre work but:

user@nuc7pjyh:~$ ps axo stat,ppid,pid,comm | grep -w defunct
Z      18289   18307 s6-notifyonchec <defunct>

## Environment
**OS:** ubuntu server 20.04
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by meLIanTQ** [comment]
when "docker container exec -it calibre sh" and run the command s6-svscan
get:
`s6-supervise boot: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise lib: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise lib64: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise etc: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise root: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise dev: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise (child): fatal: unable to exec run: No such file or directory`

**Comment by aptalca** [comment]
it's now using a different baseimage
