### ISSUE TITLE
Remote Desktop Username abc // abc, not changed by environment variables

### ISSUE THREAD

**Issue by alfonsrv** [linuxserver/docker-calibre#40]
Please include environment variables to change the default xrdp username + password from `abc`, `abc` in `/etc/xrdp/xrdp.ini` to something appropriate.

**Comment by monty-za** [comment]
Latest version of linuxserver/calibre - the environmental variables for GUAC_USER & GUAC_PASS do not work - still have to log in with abc / abc.

**Comment by j0nnymoe** [comment]
@monty-za read the change log? https://github.com/linuxserver/docker-calibre#versions
