### ISSUE TITLE
raspberry pi 4 version?

### ISSUE THREAD

**Issue by bluenote73** [linuxserver/docker-calibre#42]
I really love this image, but running it under windows is a pain. Could you consider providing a raspberry pi 4 version?  Personally that's where I run all my other lsio containers.
Thanks for all your work either way.

**Comment by aptalca** [comment]
calibre doesn't publish binaries for arm

**Comment by bluenote73** [comment]
> calibre doesn't publish binaries for arm

I don't pretend to understand the ins and outs, but it has been in the repositories for pi for quite a while. And I guess when they update their PiOS there will be a new one. Is this not good enough?
thx, sorry if this is a dumb question.

**Comment by phampyk** [comment]
Yes please, if there's any chance to have this, I just moved all my docker containers to a raspberry pi and this one is the only one I can't have. It would be amazing if there's any way to have it. Thank you

**Comment by tobbenb** [comment]
You have to ask Calibre to compile arm versions. Nothing we can do.

**Comment by danrneal** [comment]
Shouldn't pulling from arch work?  It is what the main calibre dev recommends.
