### ISSUE TITLE
Cannot connect to Guacamole on Calibre docker container 

### ISSUE THREAD

**Issue by jagadeesh-s2104** [linuxserver/docker-calibre#50]
------------------------------

## Expected Behavior

It should give guac login page.

Normally when I install the Calibre docker - I will be able to connect to the guac. But now I get error "connecting to sesman ip 127.0.0.1 port 3350"

https://imgur.com/TSw69jj 

I tried it in two different machine and a AWS VM. 
Same error. 

I used docker  compose with  "image: ghcr.io/linuxserver/calibre" (I believe this means latest)
when I change it to  "image: ghcr.io/linuxserver/calibre:version-v5.10.0" it works fine. 

## Current Behavior

https://imgur.com/TSw69jj 

## Steps to Reproduce

1. Create a container based on "image: ghcr.io/linuxserver/calibre"
2.
3.
4.

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** AMD64
**How docker service was installed:**

Compose

## Command used to create docker container (run/create/compose/screenshot)

version: "2.1"
services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: caliber
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - GUAC_USER=sdfsdf
      - GUAC_PASS=sdsdf

    volumes:
      - /home/jkumar/test-caliber-library:/config
    ports:
      - 8282:8080
      - 8283:8081
    restart: unless-stopped

**Comment by aptalca** [comment]
Post a log and you will see why

**Comment by BenevolentTumour** [comment]
I have the same issue since updating the container, as far as I know I have not changed anything else. I have attached what I believe is the log below. 

[calibrelog.txt](https://github.com/linuxserver/docker-calibre/files/6359865/calibrelog.txt)

I would really appreciate any help on how to resolve this issue.

**Comment by aptalca** [comment]
It says:
```
[36mcalibre      |[0m ********************************************************
[36mcalibre      |[0m ********************************************************
[36mcalibre      |[0m ****                                                ****
[36mcalibre      |[0m ****  GUAC_USER and GUAC_PASS vars are deprecated   ****
[36mcalibre      |[0m ****                                                ****
[36mcalibre      |[0m ****  Temporary credentials are being set:          ****
[36mcalibre      |[0m ****                                                ****
[36mcalibre      |[0m ****  User: abc                                     ****
[36mcalibre      |[0m ****  Pass: abc                                     ****
[36mcalibre      |[0m ****                                                ****
[36mcalibre      |[0m ****                                                ****
[36mcalibre      |[0m ****  See the readme for new credential info        ****
[36mcalibre      |[0m ****                                                ****
[36mcalibre      |[0m ****                                                ****
[36mcalibre      |[0m ********************************************************
[36mcalibre      |[0m ********************************************************
```

**Comment by jagadeesh-s2104** [comment]
[docker-calibre-log.txt](https://github.com/linuxserver/docker-calibre/files/6360261/docker-calibre-log.txt)
Please find the log file

**Comment by jagadeesh-s2104** [comment]
Sorry. It works!
