### ISSUE TITLE
Add  Base URL for Reverse Proxy Subfolder Support

### ISSUE THREAD

**Issue by CrypticOne** [linuxserver/docker-calibre#52]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

1. Pass base URL to docker container -> guacamole 
2. Setup Reverse Proxy to load web interface on www.somedomain.com/calibre/
3. Interface Loads correctly on both 192.168.0.100:8080/calibre and www.somedomain.com/calibre/

## Current Behavior

1. Interface Loads correctly when using 192.168.0.100:8080/
2. Interface fails to load when using www.somedomain.com/calibre/. Source shows site trying to access files in /public/ directory which does not exist. IE: /public/vendor/guac/js/guac.min.js

**Comment by CrypticOne** [comment]
#https://github.com/linuxserver/docker-baseimage-rdesktop-web/issues/3

Issue on the upstream package.

**Comment by CrypticOne** [comment]
I managed to hack up a solution. The issue seems to start in the gclient package.  @thelamer 

https://github.com/linuxserver/gclient/blob/6772097d74ce00aefa94953fe74e0bd470486ca2/rdp.ejs#L78

I edited all the refences to /public/ and /files/ to just be public/ and files/

Now it loads when connected directly or via reverse proxy.


`<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="LinuxServer Guacamole Client">
    <meta name="author" content="thelamer">
    <title>Guacamole Client</title>
    <link href="public/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="public/vendor/font-awesome/css/fontawesome.min.css" rel="stylesheet" type="text/css">
    <link href="public/css/vdi.css" rel="stylesheet" type="text/css">
    <link rel="apple-touch-icon" sizes="57x57" href="public/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="public/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="public/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="public/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="public/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="public/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="public/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="public/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="public/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="public/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="public/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="public/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="public/favicon/favicon-16x16.png">
    <link rel="manifest" href="public/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="public/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body style="overflow:hidden;">
    
    <div id="sidebar" style="cursor:initial;display:none;width:200px;height:100%;background:#353430;padding: 5px 10px;color:white;">
      
      <button type="button" class="close" aria-label="Close" style="color:white;" onclick="closeside()"><span aria-hidden="true">x</span></button>
      <center><button type="button" style="cursor:pointer;" class="btn btn-secondary" onclick="poposk()">Touch <i class="far fa-keyboard"></i></button></center>
      
      ClipBoard:<br>
      <textarea id="clipboard" class="stopcapture form-control" rows="7"></textarea>
      
      <form id="filesform" action="files" method="post" target="files_frame">
        Password:<br>
        <input type="password" value="abc" class="stopcapture form-control" name="password" placeholder="User Password" required><br>
        <center><button type="submit" style="cursor:pointer;" class="btn btn-secondary">Files <i class="far fa-file"></i></button></center>
      </form>
    </div>
    
    <div id="Keyboard" data-backdrop="false" class="modal fade lsosk" tabindex="-1" style="cursor:initial;">
      <div class="modal-dialog" style="opacity:0.5;max-width:100%!important;">
        <div class="modal-content">
          <div class="modal-body">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <div id="osk"></div>
          </div>
        </div>
      </div>
    
    <div id="files" class="modal fade" tabindex="-1" style="cursor:initial;">
      <div class="modal-dialog" style="max-width:90%!important">
        <div class="modal-content">
          <div id="files_body" class="modal-body" style="height:90vh!important">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <iframe id="files_frame" name="files_frame" src="files" frameborder="0"></iframe>
          </div>
        </div>
      </div>
    </div>
    </div>
    
    <input type="checkbox" id="nav-trigger" class="nav-trigger" />
    <label id="sidebaricon" for="nav-trigger"><i class="fa fa-arrow-right"></i></label>
    
    <div class="site-wrap" onmouseover="this.focus();" tabindex="0" style="outline:none;">
      <div id="display" style="width:100%;height:100vh;overflow:hidden;position:absolute;left:0;top:0;"></div>
    </div>
    
    <input type="hidden" id="connectionstring" value="<%- token -%>" />
    
    <script type="text/javascript" src="public/vendor/guac/js/guac.min.js"></script>
    
    <script type="text/javascript" src="public/vendor/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="public/vendor/popper/popper.min.js"></script>
    <script type="text/javascript" src="public/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="public/vendor/shortcut/js/shortcut.js"></script>
    
    <script type="text/javascript" src="public/js/rdp.js"></script>
  </body>
</html>
`

**Comment by aptalca** [comment]
https://github.com/linuxserver/reverse-proxy-confs/blob/master/calibre.subfolder.conf.sample#L2

**Comment by rbrussell82** [comment]
I tried adding the SUBFOLDER=/calibre/ Docker environment variable and the interface still fails to load when going to www.somedomain.com/calibre/ but works when going to my local IP and port like 192.168.0.100:8080/calibre/.

**Comment by aptalca** [comment]
Did you update your proxy conf?

**Comment by rbrussell82** [comment]
> Did you update your proxy conf?

Yes, I replaced my original one with the current sample that has the comment about the environment variable.  I get a blank white page that only shows the arrow on the left for the clipboard options.

**Comment by aptalca** [comment]
Check your browser plugins, disable to try (can also try incognito)

**Comment by rbrussell82** [comment]
Tried different browsers and incognito, same experience.  The black mouse pointer disappears almost right away.  Is there another way to set the base URL or is that what the environment variable does?

**Comment by aptalca** [comment]
Your base url is working as confirmed by going to the local ip with that base url

**Comment by CrypticOne** [comment]
Can you view source on the somedomain.com/calibre and see if it is trying to access any "/public" files?

**Comment by rbrussell82** [comment]
I can see that it is trying /calibre/public.

<html>
<body>


<title>Guacamole Client</title>
--
  | <link href="/calibre/public/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  | <link href="/calibre/public/vendor/font-awesome/css/fontawesome.min.css" rel="stylesheet" type="text/css">
  | <link href="/calibre/public/css/vdi.css" rel="stylesheet" type="text/css">
  | <link rel="apple-touch-icon" sizes="57x57" href="/calibre/public/favicon/apple-icon-57x57.png">
  | <link rel="apple-touch-icon" sizes="60x60" href="/calibre/public/favicon/apple-icon-60x60.png">
  | <link rel="apple-touch-icon" sizes="72x72" href="/calibre/public/favicon/apple-icon-72x72.png">
  | <link rel="apple-touch-icon" sizes="76x76" href="/calibre/public/favicon/apple-icon-76x76.png">
  | <link rel="apple-touch-icon" sizes="114x114" href="/calibre/public/favicon/apple-icon-114x114.png">
  | <link rel="apple-touch-icon" sizes="120x120" href="/calibre/public/favicon/apple-icon-120x120.png">
  | <link rel="apple-touch-icon" sizes="144x144" href="/calibre/public/favicon/apple-icon-144x144.png">
  | <link rel="apple-touch-icon" sizes="152x152" href="/calibre/public/favicon/apple-icon-152x152.png">
  | <link rel="apple-touch-icon" sizes="180x180" href="/calibre/public/favicon/apple-icon-180x180.png">
  | <link rel="icon" type="image/png" sizes="192x192"  href="/calibre/public/favicon/android-icon-192x192.png">
  | <link rel="icon" type="image/png" sizes="32x32" href="/calibre/public/favicon/favicon-32x32.png">
  | <link rel="icon" type="image/png" sizes="96x96" href="/calibre/public/favicon/favicon-96x96.png">
  | <link rel="icon" type="image/png" sizes="16x16" href="/calibre/public/favicon/favicon-16x16.png">
  | <link rel="manifest" href="/calibre/public/favicon/manifest.json">
  | <meta name="msapplication-TileColor" content="#ffffff">
  | <meta name="msapplication-TileImage" content="/calibre/public/favicon/ms-icon-144x144.png">
  | <meta name="theme-color" content="#ffffff">


</body>
</html>

And I can also see the baseurl setting:
<html>
<body>



--
  | <input type="hidden" id="connectionstring" value="xxxx" />
  | <input type="hidden" id="baseurl" value="/calibre/" />
  | 
  | <script type="text/javascript" src="/calibre/public/vendor/guac/js/guac.min.js"></script>
  | 
  | <script type="text/javascript" src="/calibre/public/vendor/jquery/jquery.min.js"></script>
  | <script type="text/javascript" src="/calibre/public/vendor/popper/popper.min.js"></script>
  | <script type="text/javascript" src="/calibre/public/vendor/bootstrap/js/bootstrap.min.js"></script>
  | <script type="text/javascript" src="/calibre/public/vendor/shortcut/js/shortcut.js"></script>
  | 
  | <script type="text/javascript" src="/calibre/public/js/rdp.js"></script>


</body>
</html>

**Comment by CrypticOne** [comment]
Looks pretty good.  Odd it isn't loading.

**Comment by thelamer** [comment]
Post any errors in your browsers console when this occurs.

**Comment by rbrussell82** [comment]
Here's what console shows when it stops:

```
WebSocket connection to 'wss://myurl.com/calibre/guaclite?token=eyJpdiI6IjNqbktlYy9SNnA4VEhiRUgxTVdSMXc9PSIsInZhbHVlIjoiVit6Wm9CbDVvRGxZRjNiRUV1VnJCYUVEN0QwS3J3WW13WFB5OTdpZEc2bEhOSmd4VmdWUjU5VmpCRy9ESHJzcnN2bTh1NzZpc0tNcGp5MXk1V0RzSzJEajBmL2FyTldaS3hUSEVZLzRNMytQeGt3YVdaM0pjWEZjeHNNZUd0VVBOc3NmT2pDdjA3cUFpRU01NkFYblVZN0VqVG12RDJ1NEJiclkxYjFtZEVPUW43WnVmY0RMbVdrY2dUbDlhL0ttaG5IOUV1YXN0enIwT3AwZTNuSlFlT0lTVDRjRmQ2N1QzMjhFcnMvYnlkVT0ifQ==&width=1407&height=1297?undefined' failed: 
connect @ guac.min.js:1
connect @ guac.min.js:1
(anonymous) @ rdp.js:90
```

**Comment by thelamer** [comment]
The path is correct so it would indicate that your proxy is not upgrading websocket requests properly.

**Comment by rbrussell82** [comment]
> The path is correct so it would indicate that your proxy is not upgrading websocket requests properly.

That pointed me in the right direction and maybe this will help someone else.  I had to add these into my calibre.subfolder.conf file and now it works:

```
    proxy_set_header Connection "Upgrade";
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Host $host;
```

**Comment by aptalca** [comment]
Those are handled in the nginx.conf
Likely your config files are out of date. The log should tell you if they are
