### ISSUE TITLE
Shutdown script

### ISSUE THREAD

**Issue by maltokyo** [linuxserver/docker-calibre#53]
Hello, I have a simple question.  When docker closes this container, is the calibre app shut down gracefully?  I seem to get corruption in files when I stop the container. 

Any tips on where the code is that shuts down the calibre app (like ctrl-Q etc on a desktop?) when the container is bought down?  Thanks!

**Comment by aptalca** [comment]
I don't think it's graceful at the moment and it's something on my list to look into. It's all handled in our rdesktop-web baseimage

**Comment by maltokyo** [comment]
ok, for me somehow the db is corrupt after each time I run `docker-compose down` - would be nice if someone can help with a way to shut calibre down as part of the container shutdown process.

**Comment by aptalca** [comment]
Did some testing, it actually is shutting down gracefully, however by default s6 supervisor only waits for 3 seconds for processes to shutdown and sends a sigkill. Sometimes calibre may take a little longer.

You can try passing this env var in your compose to increase that timeout:
`S6_KILL_GRACETIME=10000` (the value is in milliseconds)

**Comment by maltokyo** [comment]
oh thanks, that might just solve it, will try now! Great stuff.
