### ISSUE TITLE
Direct RDP login is broken after base image switch

### ISSUE THREAD

**Issue by rcarmo** [linuxserver/docker-calibre#54]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I should be able to login to the container using an RDP client and access the Calibre GUI directly

## Current Behavior

Even after removing the legacy environment variables, logging in via RDP directly throws up the Xrdp error dialog (followed by its auth dialog) and there is no way to access Calibre.

This is essential to me as Guacamole does not work correctly with Safari (and is impossible to use from an iPad via the web UI).

## Steps to Reproduce

1. Deploy container as linuxserver/calibre:latest, with full default settings and port 3389 open
2. Log in via any RDP client as “abc” with the default password
3. Xrdp error and login screen show up, calibre is not accessible
4. If port 8080 is exposed, I can see the Calibre UI via a web browser

## Environment
**OS:** Linux (plus iOS clients)
**CPU architecture:** x86_64
**How docker service was installed:**

Standard Synology package (also reproduced in Ubuntu with Docker APT repo)

## Command used to create docker container (run/create/compose/screenshot)

N/A. Synology UI defaults for the container with only port 3389 open to the outside. 
On. Ubuntu, just a plain Docker run linuxserver/calibre:latest exposing port 3389 is enough to reproduce the issue.

Screenshot of Synology GUI, since it keeps getting requested (note that PASSWORD is set and visible, which is a bad practice):

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/392683/117542601-3086b800-b011-11eb-9f8d-11b992ca4729.png">

Volume section, since I just discovered that Calibre loses its configuration even though I have `/config` mapped to the container - which worked in the previous image):

<img width="614" alt="Screen Shot 2021-05-08 at 15 32 14" src="https://user-images.githubusercontent.com/392683/117542952-9d4e8200-b012-11eb-9f86-388e13270d48.png">

## Docker logs

N/A. Synology does not provide direct access to Docker logs. Running the container manually on another machine shows the default password warning as scripted in https://github.com/linuxserver/docker-calibre/blob/master/root/etc/cont-init.d/50-config, with the message “no password is set for the interface”.

Docker log UI in Synology, since it also keeps getting requested (Github gets confused with pasting images, apologies for the multiple updates but it set all images to the same):

<img width="1239" alt="Screen Shot 2021-05-08 at 15 33 04" src="https://user-images.githubusercontent.com/392683/117542975-b7886000-b012-11eb-89ba-5dc429fe4832.png">

**Comment by tobbenb** [comment]
It's because you do not supply what we ask for. We added the issue template so you see what we need from you and don't need to use our free time to ask for the info.
But for some reason you think; hey, screw that, I'm not going to fill out a bloody template. Let these guys waste their time trying to help me.

**Comment by rcarmo** [comment]
I’m sorry, but I honestly did think the information was not required as this is a default install and the log information has no bearing on the issue (Also, Synology Docker logs are pretty much useless in general).

Also, the new auth mechanism for this new base image forces me to have cleartext passwords in the config, and screenshooting the Synology UI is… sub-optimal.

Thanks for your understanding.

**Comment by rcarmo** [comment]
Updated the issue description.

**Comment by aptalca** [comment]
Rdp access _requires_ a password so you need to use the new var and set one. You said you used the `default` password but I am 99% sure that you don't know what it is so that's not quite possible.

I can't tell you what the exact issue is because you still didn't give us the docker args you used or provided a log.

Also, keep in mind that rdp access is not something we officially support or optimize for or advertise for this container. But in any case, it still works.

**Comment by rcarmo** [comment]
I thought it was obvious that I'm using the container in a Synology NAS, which does not have a CLI or logs that work the same way.

Yesterday I spun up an Azure VM for a quick test with the same results, but allow me to explain again: Even if I can log in successfully, I get different results via direct RDP and via Guacamole. Via Guacamole I can see the UI, via RDP I cannot, it just errors out.

**Comment by rcarmo** [comment]
I've updated the ticket with what I can get out of the Synology UI. The logs are in HTML or CSV format when exported, I assume you probably don't want those in that format as (like I said in the beginning) they are useless.

**Comment by rcarmo** [comment]
Another related issue: Calibre keeps losing the config upon container restart, and I have to reconfigure everything (including e-mail settings) every time it runs (and yes, I have `/config` mounted, like i the previous container image):

<img width="892" alt="image" src="https://user-images.githubusercontent.com/392683/117542797-f5d14f80-b011-11eb-916e-6f8798599f58.png">

**Comment by j0nnymoe** [comment]
@rcarmo not related to the actual issue but a recommendation is to use docker-compose instead of using the Synology DSM GUI. Makes management of containers a lot easier (you can still use the DSM to monitor the containers if needed)

**Comment by rcarmo** [comment]
> @rcarmo not related to the actual issue but a recommendation is to use docker-compose instead of using the Synology DSM GUI. Makes management of containers a lot easier (you can still use the DSM to monitor the containers if needed)

Thanks, but I don't want to use docker-compose inside the new Synology models as they keep breaking the CLI. I have decided to use the new Intel models as dumb appliances as there is way less opportunity to hack these like the old ARM5 versions.

**Comment by j0nnymoe** [comment]
Not sure what you mean by breaking the cli but I've had the groups Synology box running with zero issues for the 1+ year we've had it.
