### ISSUE TITLE
Calibre loses configuration upon container restart

### ISSUE THREAD

**Issue by rcarmo** [linuxserver/docker-calibre#55]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I should be able to restart the container without losing the Calibre configuration

## Current Behavior

When I restart the container, Calbre has lost all its configuration (library location, e-mail server settings, UI layout preferences, e-reader model, etc.) and I have to reconfigure everything again, even though I have a persistent `/config` folder and no permissions issues.

## Steps to Reproduce

1. Deploy container as linuxserver/calibre:latest, with `/config` correctly mapped to the Synology filesystem and a separete `/books` volume with exactly the same permissions
2. Configure once.
3. Restart the container in an attempt to diagnose #54 and #51 
4. Calibre displays the startup screen again:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/392683/117542797-f5d14f80-b011-11eb-916e-6f8798599f58.png">

## Environment
**OS:** Synology DSM
**CPU architecture:** x86_64
**How docker service was installed:**

Standard Synology package

## Command used to create docker container (run/create/compose/screenshot)

Screenshot of Synology GUI, since it keeps getting requested (note that PASSWORD is set and visible, which is a bad practice):

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/392683/117542601-3086b800-b011-11eb-9f8d-11b992ca4729.png">

Volume section, which worked in the previous base image:

<img width="614" alt="Screen Shot 2021-05-08 at 15 32 14" src="https://user-images.githubusercontent.com/392683/117542952-9d4e8200-b012-11eb-9f86-388e13270d48.png">

## Docker logs

Docker log UI in Synology 

<img width="1239" alt="Screen Shot 2021-05-08 at 15 44 45" src="https://user-images.githubusercontent.com/392683/117543352-5e213080-b014-11eb-98be-9ff7eb33ee2a.png">

**Comment by j0nnymoe** [comment]
Delete the 'HOME=/root` environment variable and this should fix it.

**Comment by rcarmo** [comment]
I just tried that, fhanks, but it does not work. Calibre comes up again showing "/root" as the location for my books, and seems to completely ignore `/config` no matter what I do. 

I've checked the modification dates for the `docker/calibre` folder I have mapped to `/config` and the only files that were modified today are Xrdp logs, so I'm assuming it's writing the configuration someplace else:

<img width="1070" alt="Screen Shot 2021-05-08 at 15 57 53" src="https://user-images.githubusercontent.com/392683/117543800-48ad0600-b016-11eb-89ae-7fa67b9a9817.png">

**Comment by rcarmo** [comment]
I have been digging around a bit inside the new container image, and I think the init script has a bug, because of the following.

This is what I can see when I restart the container and Calibre is auto-started. Note that it is possible to get a terminal window going now (not sure if by design or just leaving Openbox with defaults, but I'll skip the possible security issues for the moment), and that I can see what file descriptors the first instance of Calibre tries to open (or, rather, the ones it has open that very moment):

<img width="1308" alt="Screen Shot 2021-05-08 at 16 12 31" src="https://user-images.githubusercontent.com/392683/117544282-a2163480-b018-11eb-9db1-b85c6166954d.png">

The interesting thing is that _if I kill that Calibre instance and start a fresh one from the terminal_ the new one does, in fact, start correctly and opens the right files from the right places:

<img width="1308" alt="Screen Shot 2021-05-08 at 16 12 31" src="https://user-images.githubusercontent.com/392683/117544306-bd813f80-b018-11eb-8940-6347529febee.png">

So the configuration is now persisted, but the initial Calibre instance does not even try to get it for some reason - which leads me to the conclusion the init script is flawed somehow.

(Also, at least now I can try to rebuild the rather complex configuration I had for the previous base image, since that got overwritten somehow during all these tests and I will need to recover it from a Synology snapshot...)

So please check what is going on when the initial instance is launched. I can try to `strace` the process or figure out its starting environment, but I suppose more testing is required at your end...

**Comment by aptalca** [comment]
Delete the var `HOME=/root` and recreate the container.

https://github.com/linuxserver/docker-calibre/issues/48#issuecomment-823335892

**Comment by rcarmo** [comment]
> Delete the var `HOME=/root` and recreate the container.
> 
> [#48 (comment)](https://github.com/linuxserver/docker-calibre/issues/48#issuecomment-823335892)

Maybe it wasn't obvious, but I already did that. Twice. 

(Synology has an option to "clear" the container in the UI that I use upon every update, which does a `docker rm`).

**Comment by j0nnymoe** [comment]
![image](https://user-images.githubusercontent.com/10374553/117546087-9595da00-b020-11eb-9324-6671b0b1a643.png)

**Comment by rcarmo** [comment]
> > Delete the var `HOME=/root` and recreate the container.
> > [#48 (comment)](https://github.com/linuxserver/docker-calibre/issues/48#issuecomment-823335892)
> 
> Maybe it wasn't obvious, but I already did that. Twice.
> 
> (Synology has an option to "clear" the container in the UI that I use upon every update, which does a `docker rm`).

Maybe my original point did not get across. I already did that.

**Comment by j0nnymoe** [comment]
> > > Delete the var `HOME=/root` and recreate the container.
> > > [#48 (comment)](https://github.com/linuxserver/docker-calibre/issues/48#issuecomment-823335892)
> > 
> > 
> > Maybe it wasn't obvious, but I already did that. Twice.
> > (Synology has an option to "clear" the container in the UI that I use upon every update, which does a `docker rm`).
> 
> Maybe my original point did not get across. I already did that.

You need to be deleting and recreating the container with the latest image pulled. I did this on our syno box and it's worked fine.

**Comment by rcarmo** [comment]
You don't need to _delete_ the container. If you right-click on it and do "clear", Synology does a `docker rm`. However, in my case, that has not cleared up the issue yet. I will try pulling the image again, but your debug step is equivalent to mine (except that I don't have to re-enter the config).

**Comment by j0nnymoe** [comment]
Issue is, it's not clearing the environment variables like you would expect with docker-compose which is why your HOME shows `/root` instead of config.

**Comment by rcarmo** [comment]
I have already removed that as well. Please read the comments more thoroughly.

**Comment by j0nnymoe** [comment]
Yea I am reading them 😊

**Comment by rcarmo** [comment]
I have already done that, so I am now waiting for my NAS to reboot.

**Comment by pparedes1** [comment]
I was having this same issue on my synology and had not noticed that the container's HOME variable was pointing to /root so I had to delete and recreate the container (as other have suggested). Actually I re-created the container using docker-compose but had to change all my variables to the minimum. The OP perfers not using docker-compose and seems to be having issues with either re-creating the container or his configuration folder that might have been messed up with the upgrade. Two suggestions:

1) Create a new blank config folder or just rename the current docker/calibre folder and re-create docker/config folder

   - You can go through the set up once and close down the container and restart. If your settings are saved you can move things like plugins from your renamed config folder as needed. 

2) Confirm the details of your container by sharing the parameters for the running container. If you have ssh access, can you post the details of the following command? 

`docker run --rm -v/var/run/docker.sock:/var/run/docker.sock assaflavie/runlike calibre-test` 

   This assumes the name of the container is 'calibre-test' per the screen shot but you can change name below if it's called something else.
