### ISSUE TITLE
Resizing the browser window logs out Guacamole session

### ISSUE THREAD

**Issue by rcarmo** [linuxserver/docker-calibre#56]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I should be able to resize the browser window with no consequences, as in the previous base image.

## Current Behavior

When I resize my browser, I am forced to login again.

## Steps to Reproduce

1. Deploy container as linuxserver/calibre:latest, just as described in #55.
2. Log in once.
3. Resize the browser as shown in this screen recording:

![Screen Recording 2021-05-08 at 16 25 44](https://user-images.githubusercontent.com/392683/117544810-fcb09000-b01a-11eb-907d-5ab22dbd9fe0.gif)

4. Log in again.

## Environment
**OS:** Synology DSM
**CPU architecture:** x86_64
**How docker service was installed:**

Standard Synology package

## Command used to create docker container (run/create/compose/screenshot)

Screenshot of Synology GUI:

<img width="1240" alt="Screen Shot 2021-05-08 at 16 33 44" src="https://user-images.githubusercontent.com/392683/117544843-2cf82e80-b01b-11eb-89a4-e09d4aac2392.png">

Volume section, same as #55 (no changes):

<img width="614" alt="Screen Shot 2021-05-08 at 15 32 14" src="https://user-images.githubusercontent.com/392683/117542952-9d4e8200-b012-11eb-9f86-388e13270d48.png">

## Docker logs

Docker log UI in Synology 

<img width="1240" alt="Screen Shot 2021-05-08 at 16 35 19" src="https://user-images.githubusercontent.com/392683/117544896-65980800-b01b-11eb-95b4-e2d6cf612317.png">

**Comment by aptalca** [comment]
I believe that's gclient behavior where it refreshes the whole thing when the window resolution changes.

You can remove the built-in auth and instead protect it via your reverse proxy

**Comment by thelamer** [comment]
This is default behavior and expected, it is the best way to keep a pixel perfect render. 

I get it is a pain in the ass if you have a password set, but a full window reload was the only way I found this worked across all browsers. 

If you want to fork off an remove this the code is here: 
https://github.com/linuxserver/gclient/blob/master/public/js/rdp.js#L175-L183

**Comment by rcarmo** [comment]
Well, I suppose trying to use a window manager that would be resize-aware inside Xrdp isn’t feasible then? I’ve had a decent experience with modern Xrdp builds in Ubuntu LTS…
