### ISSUE TITLE
Config is wiped after update

### ISSUE THREAD

**Issue by daborbor** [linuxserver/docker-calibre#57]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
The current configuration should be wiped.

## Current Behavior
After recreating the image, the first time setup dialog showed up.

## Steps to Reproduce

1. Redeploy the image
2. Open the guacamole url

## Environment
**OS:*Linux Debian*
**CPU architecture:** x86_64
**How docker service was installed:**
From official Docker via portainer

## Command used to create docker container (run/create/compose/screenshot)

![image](https://user-images.githubusercontent.com/7836056/120510201-b7347800-c3b8-11eb-9b4b-b849e057f429.png)

**Comment by daborbor** [comment]
Going through the logs it seems like I recreated the image by accident

**Comment by aptalca** [comment]
Don't use portainer. It keeps setting this environment var: `HOME=/root`, which is breaking it. We set `HOME=/config` inside the container, which is the correct value, but portainer is overriding it.
