### ISSUE TITLE
News Feed not working on version 5.23

### ISSUE THREAD

**Issue by jmartinezs77** [linuxserver/docker-calibre#60]
Hi, 

I am running docker-calibre on a Synology NAS. Today I updated to versión 5.23 and when trying to download some news feed, I got the following error:

____________________________
calibre, version 5.23.0
ERROR: Excepción no considerada: <b>FileNotFoundError</b>:[Errno 2] No such file or directory

calibre 5.23  embedded-python: True is64bit: True
Linux-4.4.59+-x86_64-with-glibc2.2.5 Linux ('64bit', '')
('Linux', '4.4.59+', '#25556 SMP PREEMPT Thu Mar 18 13:00:34 CST 2021')
Python 3.8.5
Interface language: es
Traceback (most recent call last):
  File "calibre/gui2/dialogs/scheduler.py", line 689, in download_clicked
  File "calibre/gui2/dialogs/scheduler.py", line 714, in download
  File "calibre/gui2/dialogs/scheduler.py", line 698, in has_internet_connection
  File "calibre/utils/network.py", line 108, in internet_connected
  File "calibre/utils/network.py", line 41, in __init__
  File "calibre/utils/network.py", line 61, in nm
  File "calibre/utils/network.py", line 49, in connect
  File "jeepney/io/blocking.py", line 245, in open_dbus_connection
FileNotFoundError: [Errno 2] No such file or directory
________________________

I have tried to find the jeepney directory but I can't find it anywhere.
¿Any idea on how to install it?

Many thanks

**Comment by gbull1993** [comment]
Exact same issue here. Hoping for a fix :)

**Comment by jutzin** [comment]
Ditto.

**Comment by chimpboy** [comment]
Same issue here. Did this work on previous versions?

**Comment by chimpboy** [comment]
FYI, I have resolved this (temporarily) by reverting to version 5.23. I did this by changing the repository for my docker to linuxserver/calibre@sha256:b795c24996d9b06722c853214ed3394e45283eda6159f125822d2ae71edc49d5

**Comment by jutzin** [comment]
> Same issue here. Did this work on previous versions?

Yes, it did work up to and including v5.22.

**Comment by woutervanranst** [comment]
same issue here

**Comment by bvarick** [comment]
I had the same problem and v5.25.0-ls124 works again. None of the other versions since v5.22.1 worked, but it seems to be fixed now.

**Comment by chimpboy** [comment]
Thanks for letting us know!

**Comment by jutzin** [comment]
Yeah, many thanks!
