### ISSUE TITLE
How to add new books from a local PC?

### ISSUE THREAD

**Issue by dlsnet** [linuxserver/docker-calibre#63]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by jschwalbe** [comment]
This may be more of a calibre question than a linuxserver question, per se, but what sort of files go in this directory. I have exported from my main machine and have files like `part-0001.calibre-data` etc. I've moved it to a directory on the host and shared it as /import, but I don't see anything upon relaunching calibre.
