### ISSUE TITLE
No Web Browser - Cannot Auth. News from Pocket Plus Recipe

### ISSUE THREAD

**Issue by invalidx** [linuxserver/docker-calibre#65]
I have configured the Pocket Plus recipe from https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin
Normally, upon the first run of the recipe it will request authentication from a web browser window. As no browser is included in this container, I am unable to use the recipe.

Is there an authentication workaround or can a browser be added to this?

------------------------------

## Desired Behavior
First Run of Pocket Plus should open web browser to input login details

## Current Behavior
Calibre shows pop-up with hyperlink to open browser and log in to pocket. Clicking this has no result.

**Comment by aptalca** [comment]
you can install a browser via customization: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
