### ISSUE TITLE
client at 8080 behind nginx proxy manager

### ISSUE THREAD

**Issue by Albrod** [linuxserver/docker-calibre#69]
Just adding this to share how i made it work
Would be great to have this at the readme

In NPM add a custom location for /
pointing to the same place
add these configuration using the cogwheel at the rigth

add_header    X-Served-By    $host;
proxy_cookie_path    /guacamole/    /;
proxy_http_version    1.1;
proxy_set_header    Upgrade      $http_upgrade;
proxy_set_header    Connection $http_connection;
include conf.d/include/force-ssl.conf;

I got this from here, it works like a charm
[https://www.reddit.com/r/selfhosted/comments/fvdmio/need_guacamole_nginx_help/](url)
    
    
![image](https://user-images.githubusercontent.com/9517199/149677169-4f070944-636c-4b6d-9de4-47982346b5b8.png)
![image](https://user-images.githubusercontent.com/9517199/149677196-5491e340-d3af-44fa-ab61-f82a6b4f377c.png)

**Comment by clemans** [comment]
@Albrod  Just wanted to say thank you for taking the time to document this! Huge help and the configuration works like a charm!
