### ISSUE TITLE
Setting password causes login failure

### ISSUE THREAD

**Issue by SSoft7** [linuxserver/docker-calibre#70]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Should login fine

## Current Behavior

error: login failed for disaplay 0

## Steps to Reproduce

1. Just set the PASSWORD env variable and run.
2. If you run without setting any password it just works fine.

## Environment
**OS:** Ubuntu Bionic
**CPU architecture:** x86_64
**How docker service was installed:** official repo

## Command used to create docker container (run/create/compose/screenshot)

```
docker run -d \
  --name=calibre \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e PASSWORD=abc \
  -p 8080:8080 \
  -p 8081:8081 \
  -v /path/to/data:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/calibre
```

## Docker logs

Too much logs

**Comment by tobbenb** [comment]
Please add logs.

**Comment by tobbenb** [comment]
Did you try to click ok on the error screen?

**Comment by SSoft7** [comment]
@tobbenb I think commit #72 fixed this issue. However, note that If i use password `abc` it does not ask for any password, but anything other than abc brings the password prompt.
