### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7)

### ISSUE THREAD

**Issue by emiksTT** [linuxserver/docker-calibre#77]
```
  ___      _           _     _   _   _  ____ _
 / _ \  __| |_ __ ___ (_) __| | | | | |/ ___/ |
| | | |/ _` | '__/ _ \| |/ _` | | |_| | |   | |
| |_| | (_| | | | (_) | | (_| | |  _  | |___| |
 \___/ \__,_|_|  \___/|_|\__,_| |_| |_|\____|_|
```
`root@strzecha:~# lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              8
Model name:          Cortex-A7`
Welcome to Armbian 22.02.1  with Linux 5.4.181-odroidxu4

System load:   3%               Up time:       9 days 11:07
Memory usage:  40% of 1.94G     IP:            172.20.0.1 172.18.0.1 172.17.0.1 192.168.10.14
CPU temp:      54°C             Usage of /:    41% of 28G
storage/:      35% of 938G

[ 0 security updates available, 15 updates total: apt upgrade ]
Last check: 2022-03-19 00:00

[ General system configuration (beta): armbian-config ]

Last login: Fri Mar 18 23:13:52 2022 from 192.168.10.20
```
root@strzecha:~# docker run -d \
  --name=calibreserver \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e PASSWORD= `#optional` \
  -e CLI_ARGS= `#optional` \
  -p 8082:8080 \
  -p 8081:8081 \
  -v /var/lib/docker/volumes/calibre_server/_data:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/calibre
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
93de4dd2443f5c07a6cc601f574318b54ed2923049527ae5f22ba48c63323445
root@strzecha:~#
```

**Comment by j0nnymoe** [comment]
You need to use the arch based images as they have arm support: https://github.com/linuxserver/docker-calibre#version-tags
