### ISSUE TITLE
Automatic adding doesn't work

### ISSUE THREAD

**Issue by ljo123** [linuxserver/docker-calibre#83]
I created a directory to monitor and enabled the auto add function but when I drop a book in that folder nothing happens. In the normal Calibre app it will auto-add to the library and move the file. Also, if I manually add the book from that same location via the web GUI, it is not auto-converted to my preferred output format (file is epub, preferred is mobi).

**Comment by ngocphamm** [comment]
This actually works for me with on Raspbian 64-bit. I got the latest build of `arch`.

**Comment by drizuid** [comment]
template not filled out, not enough info
