### ISSUE TITLE
Feature req: Autostart calibre upon container start

### ISSUE THREAD

**Issue by rodalpho** [linuxserver/docker-calibre#84]
## Desired Behavior
I have this container running on a synology NAS, primarily used for the calibre content server (CCS) daemon, but also interactively in the GUI every week or two. For some reason, it intermittently stops working. 

I can periodically restart the container via cron no problem, but the issue there is that calibre itself (/opt/calibre/bin/calibre) does not autostart when the container does-- it only starts when you interactively connect to guacamole. And the CCS doesn't start until the GUI calibre does.

(Note: Yes I could run the CCS in a separate container, but then when I want to use the GUI I'd need to stop the CCS-only container first as calibre doesn't like conflicts and must be local. That's why I'm running it on the NAS in the first place rather than over SMB from a linux box.)

Now I hacked together a way to fix that too, attaching to the container in shell, exporting my LD_LIBRARY_PATH and DISPLAY variables, and then running calibre from the CLI, and this seems to work, but the DISPLAY could change upon container restart and it's generally an ugly solution. 

My request is for an environment variable to auto-start calibre when the container starts, as opposed to when a user connects to guacamole.

## Current Behavior
Calibre doesn't start until you connect to guac

## Alternatives Considered
Ugly solution described above

**Comment by aptalca** [comment]
That feature is already implemented. It should autostart. If it's not starting, then there's a bug.

**Comment by aptalca** [comment]
fixed in #85

**Comment by rodalpho** [comment]
Thanks! Really appreciate it.
