### ISSUE TITLE
Connection breaks on my mac

### ISSUE THREAD

**Issue by Thumpermat** [linuxserver/docker-calibre#88]
I have docker-calibre installed on my synology  and  I access it in my local network with <nasip:8080>. 

It seems that since the last update I'm having connections breaks. In the logs I get:
```
[2022-06-21 13:03:22] [Connection 3]  Closing connection with error:  1006
[2022-06-21 13:03:22] [Connection 3]  Closing guacd connection
[2022-06-21 13:03:22] [Connection 3]  Client connection closed
guacd[574]: ERROR:	User is not responding.
guacd[574]: INFO:	User "@de1849b1-f77f-4127-9ea2-f5c582aea503" disconnected (0 users remain)
guacd[574]: INFO:	Last user of connection "$ec4c2fc4-8a8e-4cb7-bd2e-b270af9f13c8" disconnected
guacd[574]: INFO:	Internal RDP client disconnected
guacd[465]: INFO:	Connection "$ec4c2fc4-8a8e-4cb7-bd2e-b270af9f13c8" removed.
rdpClientConRecv: g_sck_recv failed(returned 0)
rdpClientConRecvMsg: error
rdpClientConCheck: rdpClientConGotData failed
rdpClientConDisconnect:
rdpRemoveClientConFromDev: removing clientCon 0x558ac8c65b50
```

Although I'm active on the client like moving window or button clicking. 

This disconnection happens after about 20 seconds or less.

Let me know which information you require

**Comment by j0nnymoe** [comment]
We require the information requested in the issue template.

**Comment by WombleWoo7547** [comment]
Docker desktop sometimes has issues with update automaticcally. If you open the GUI and check for updates manually
