### ISSUE TITLE
WebUI resolution 

### ISSUE THREAD

**Issue by frakman1** [linuxserver/docker-calibre#9]
Unraid Server : Version: 6.7.2 
I use Unraid server to launch this docker container. Default settings.
My issue is that the web UI resolution is very low and looks chunky

**I was wondering if there was a way to increase the resolution of the web UI.**

My Calibre docker settings:
![image](https://user-images.githubusercontent.com/5826484/65248330-00974380-dac0-11e9-87e4-b1a7b9de786d.png)

**Comment by aptalca** [comment]
Try resizing the window and then hit refresh
It should automatically rescale
