### ISSUE TITLE
ARM64 Ubuntu-based images

### ISSUE THREAD

**Issue by wietsedv** [linuxserver/docker-calibre#92]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Since Calibre 6 supports ARM, could ARM be added in to the Ubuntu-based `latest` tag?

------------------------------

## Desired Behavior

ARM-based images for the regular `latest` tag.

## Current Behavior

Only the `arch` tag contains Calibre with (unofficial) arm64 support.

## Alternatives Considered

Keep using the Arch-based tag.

**Comment by fivestones** [comment]
I'd love to see this too.

**Comment by brettinternet** [comment]
Is this not already the case? https://hub.docker.com/r/linuxserver/calibre/tags

**Comment by aptalca** [comment]
Yes, it's been added since this requests
