### ISSUE TITLE
housing metadata.db file separate from Books repository

### ISSUE THREAD

**Issue by dreg35** [linuxserver/docker-calibre#94]
Is it possible to have your metadata.db file housed in a separate folder than the books repository? I've tried the CALIBRE_OVERRIDE_DATABASE_PATH but I keep getting a permissions error. Although I can map that same folder as a volume and get access to it, but the only option in the UI is to move the entire library, which I don't want to do. Here is my [docker file](https://gist.github.com/dreg35/c1a19248de3f045024c5c5d42d5957ea). I'm running a Raspi with OMV/Docker/Portainer. 
Thanks!

**Comment by drizuid** [comment]
We do not offer any support for this type of thing. If you're able to do it, you're welcome to as it's your container. We will not support or assist with it though.
