### ISSUE TITLE
Start content server on load

### ISSUE THREAD

**Issue by ronstone2000** [linuxserver/docker-calibre#98]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Ability to optionally start the Calibre content server on container start and to override default port.

## Current Behavior
This does not appear to be possible using current parameter set.

**Comment by aptalca** [comment]
It already does once you enable it in the gui and configure the port properly, as explained in the readme: https://github.com/linuxserver/docker-calibre#application-setup
