### ISSUE TITLE
Make page title more descriptive or even editable

### ISSUE THREAD

**Issue by dkadioglu** [linuxserver/docker-calibre#99]
## Desired Behavior
The page title in the browser should be more descriptive, e.g. 'Calibre'. It would be even better, if this could be adapted by an Docker environment variable. What I am unsure about is, if this image is the right place. Maybe, such change should be made in one of
docker-rdesktop or docker-baseimage-rdesktop or docker-baseimage-rdesktop-web? Then any guacamole based linuxserver image would allow to set a more descriptive page title.

## Current Behavior
Currently the page title in the browser is 'Guacamole Client', which is too generic, I think. Especially, if you also use similar containers, e.g. Webtop, at the same time and you have two tabs with different applications but, the same title.

## Alternatives Considered
As far as I can see, the page title is not modifiable at runtime currently. However, I think, that in some older version of this container, this was possible. In a old version, which I built for myself years ago, I found the file `root/etc/cont-init.d/13-update_app_name`, which does this, I think:
```
#!/usr/bin/with-contenv bash

APPNAME=${APPNAME}
sed -i -e "s#GUI_APPLICATION#$APPNAME#" /etc/xrdp/xrdp.ini
```
I think, such change would be a nice improvement for most users. If you've got questions, or not all above is understandable, please ask. Thanks for thinking about this!

**Comment by dkadioglu** [comment]
Calming the stale bot.
As there was no reply so far, may I ask again, what your opinion about this is?

**Comment by drizuid** [comment]
We welcome PRs!

**Comment by dkadioglu** [comment]
I did a PR for one way achieving this: https://github.com/linuxserver/docker-calibre/pull/109

**Comment by dkadioglu** [comment]
I am closing this, as this is implemented with https://github.com/linuxserver/docker-calibre/pull/114. Thank you very much.
